"""add_missing_task_columns

Revision ID: 7f1bddf31319
Revises: d05714ca6977
Create Date: 2026-03-23 20:52:14.273369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f1bddf31319'
down_revision: Union[str, None] = 'd05714ca6977'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sdd_tasks', sa.Column('requirement_duration_hours', sa.Integer(), nullable=False))
    op.add_column('sdd_tasks', sa.Column('total_cost_usd', sa.Float(), nullable=False))
    op.add_column('sdd_tasks', sa.Column('total_duration_ms', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sdd_tasks', 'total_duration_ms')
    op.drop_column('sdd_tasks', 'total_cost_usd')
    op.drop_column('sdd_tasks', 'requirement_duration_hours')
    # ### end Alembic commands ###
