"""Init tables

Revision ID: d05714ca6977
Revises: 
Create Date: 2026-03-22 20:41:11.574820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd05714ca6977'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('workspaces',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sdd_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('creator_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('spec_doc_path', sa.String(length=500), nullable=True),
    sa.Column('project_path', sa.String(length=500), nullable=False),
    sa.Column('git_repo_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'BRAINSTORMING', 'PLANNING', 'CODING', 'TESTING', 'REVIEWING', 'DEPLOYING', 'DONE', 'FAILED', 'SUSPENDED', name='taskstatus'), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('current_phase', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sdd_tasks_creator_id'), 'sdd_tasks', ['creator_id'], unique=False)
    op.create_index(op.f('ix_sdd_tasks_workspace_id'), 'sdd_tasks', ['workspace_id'], unique=False)
    op.create_table('workspace_members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'DEVELOPER', 'VIEWER', name='workspacerole'), nullable=False),
    sa.Column('joined_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_members_user_id'), 'workspace_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_workspace_members_workspace_id'), 'workspace_members', ['workspace_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('creator_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='messagerole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_type', sa.Enum('TEXT', 'THINKING', 'PLAN_CARD', 'PROGRESS_CARD', 'TEST_REPORT_CARD', 'HITL_BOOLEAN', 'HITL_SELECT', 'FILE_UPLOAD', 'ERROR', name='messagetype'), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['sdd_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_task_id'), 'chat_messages', ['task_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_workspace_id'), 'chat_messages', ['workspace_id'], unique=False)
    op.create_table('sdd_assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('creator_id', sa.String(length=36), nullable=False),
    sa.Column('asset_type', sa.Enum('SPEC', 'PROMPT', 'DESIGN_DOC', 'PLAN', 'CODE_DIFF', 'UT_REPORT', 'E2E_REPORT', 'ERROR_STACK', name='assettype'), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('content_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['sdd_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sdd_assets_task_id'), 'sdd_assets', ['task_id'], unique=False)
    op.create_index(op.f('ix_sdd_assets_workspace_id'), 'sdd_assets', ['workspace_id'], unique=False)
    op.create_table('sdd_dashboard_metrics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('metric_type', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['sdd_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sdd_dashboard_metrics_task_id'), 'sdd_dashboard_metrics', ['task_id'], unique=False)
    op.create_index(op.f('ix_sdd_dashboard_metrics_workspace_id'), 'sdd_dashboard_metrics', ['workspace_id'], unique=False)
    op.create_table('sdd_plan_nodes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('creator_id', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'PASSED', 'FAILED', 'SKIPPED', name='plannodestatus'), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['sdd_plan_nodes.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['sdd_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sdd_plan_nodes_task_id'), 'sdd_plan_nodes', ['task_id'], unique=False)
    op.create_index(op.f('ix_sdd_plan_nodes_workspace_id'), 'sdd_plan_nodes', ['workspace_id'], unique=False)
    op.create_table('sdd_execution_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('creator_id', sa.String(length=36), nullable=False),
    sa.Column('plan_node_id', sa.String(length=36), nullable=True),
    sa.Column('phase', sa.Enum('BRAINSTORM', 'GIT_WORKTREE', 'PLAN', 'CODE', 'UT', 'CODE_REVIEW', 'BUILD', 'E2E_UI', 'E2E_API', name='phase'), nullable=True),
    sa.Column('log_type', sa.Enum('STDOUT', 'STDERR', 'STATUS', 'HITL_REQUEST', 'HITL_RESPONSE', 'AGENT_STATE', name='logtype'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['plan_node_id'], ['sdd_plan_nodes.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['sdd_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sdd_execution_logs_task_id'), 'sdd_execution_logs', ['task_id'], unique=False)
    op.create_index(op.f('ix_sdd_execution_logs_workspace_id'), 'sdd_execution_logs', ['workspace_id'], unique=False)
    op.create_table('sdd_test_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('creator_id', sa.String(length=36), nullable=False),
    sa.Column('plan_node_id', sa.String(length=36), nullable=True),
    sa.Column('test_type', sa.Enum('UT', 'E2E_UI', 'E2E_API', 'E2E_FULL', name='testtype'), nullable=False),
    sa.Column('test_name', sa.String(length=300), nullable=False),
    sa.Column('status', sa.Enum('PASS', 'FAIL', 'ERROR', 'SKIP', name='teststatus'), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('report_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['plan_node_id'], ['sdd_plan_nodes.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['sdd_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sdd_test_results_task_id'), 'sdd_test_results', ['task_id'], unique=False)
    op.create_index(op.f('ix_sdd_test_results_workspace_id'), 'sdd_test_results', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sdd_test_results_workspace_id'), table_name='sdd_test_results')
    op.drop_index(op.f('ix_sdd_test_results_task_id'), table_name='sdd_test_results')
    op.drop_table('sdd_test_results')
    op.drop_index(op.f('ix_sdd_execution_logs_workspace_id'), table_name='sdd_execution_logs')
    op.drop_index(op.f('ix_sdd_execution_logs_task_id'), table_name='sdd_execution_logs')
    op.drop_table('sdd_execution_logs')
    op.drop_index(op.f('ix_sdd_plan_nodes_workspace_id'), table_name='sdd_plan_nodes')
    op.drop_index(op.f('ix_sdd_plan_nodes_task_id'), table_name='sdd_plan_nodes')
    op.drop_table('sdd_plan_nodes')
    op.drop_index(op.f('ix_sdd_dashboard_metrics_workspace_id'), table_name='sdd_dashboard_metrics')
    op.drop_index(op.f('ix_sdd_dashboard_metrics_task_id'), table_name='sdd_dashboard_metrics')
    op.drop_table('sdd_dashboard_metrics')
    op.drop_index(op.f('ix_sdd_assets_workspace_id'), table_name='sdd_assets')
    op.drop_index(op.f('ix_sdd_assets_task_id'), table_name='sdd_assets')
    op.drop_table('sdd_assets')
    op.drop_index(op.f('ix_chat_messages_workspace_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_task_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_workspace_members_workspace_id'), table_name='workspace_members')
    op.drop_index(op.f('ix_workspace_members_user_id'), table_name='workspace_members')
    op.drop_table('workspace_members')
    op.drop_index(op.f('ix_sdd_tasks_workspace_id'), table_name='sdd_tasks')
    op.drop_index(op.f('ix_sdd_tasks_creator_id'), table_name='sdd_tasks')
    op.drop_table('sdd_tasks')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
