"""Add transactional global search and stable message ordering.

Revision ID: d5f60718293a
Revises: c4e5f6a7b8d9
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision = "d5f60718293a"
down_revision = "c4e5f6a7b8d9"
branch_labels = None
depends_on = None


def upgrade():
    op.add_column("chat_messages", sa.Column("sort_seq", sa.BigInteger(), nullable=True))
    op.add_column("sdd_tasks", sa.Column("next_chat_seq", sa.BigInteger(), nullable=True))
    op.create_index("ix_chat_message_context", "chat_messages", ["task_id", "created_at", "sort_seq", "id"])
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_document_states',
    sa.Column('entity_key', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('source_version', sa.BigInteger(), nullable=False),
    sa.Column('projection_hash', sa.String(length=64), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"), nullable=False),
    sa.PrimaryKeyConstraint('entity_key')
    )
    op.create_index('ix_search_state_workspace', 'search_document_states', ['workspace_id', 'entity_key'], unique=False)
    op.create_index('ix_search_state_task', 'search_document_states', ['task_id', 'entity_key'], unique=False)
    op.create_table('search_outbox',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('event_kind', sa.String(length=24), nullable=False),
    sa.Column('entity_key', sa.String(length=80), nullable=True),
    sa.Column('source_version', sa.BigInteger(), nullable=True),
    sa.Column('workspace_id', sa.String(length=36), nullable=True),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('scan_cursor', sa.String(length=160), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('available_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"), nullable=False),
    sa.Column('lease_token', sa.String(length=36), nullable=True),
    sa.Column('lease_until', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error_code', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"), nullable=False),
    sa.Column('finished_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_kind', 'entity_key', 'source_version', name='uq_search_outbox_version')
    )
    op.create_index('ix_search_outbox_lease', 'search_outbox', ['status', 'lease_until', 'id'], unique=False)
    op.create_index('ix_search_outbox_pending', 'search_outbox', ['status', 'available_at', 'id'], unique=False)
    op.create_table('search_embedding_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('endpoint', sa.String(length=500), nullable=False),
    sa.Column('model_id', sa.String(length=200), nullable=False),
    sa.Column('encrypted_api_key', sa.Text(), nullable=True),
    sa.Column('dimension', sa.Integer(), nullable=True),
    sa.Column('chunk_chars', sa.Integer(), nullable=False),
    sa.Column('chunk_overlap', sa.Integer(), nullable=False),
    sa.Column('query_prefix', sa.String(length=200), nullable=False),
    sa.Column('document_prefix', sa.String(length=200), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=True),
    sa.Column('last_error_code', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('search_index_targets',
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('physical_index', sa.String(length=120), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('embedding_profile_id', sa.String(length=36), nullable=True),
    sa.Column('dimension', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('activation_phase', sa.String(length=24), nullable=True),
    sa.Column('activation_token', sa.String(length=36), nullable=True),
    sa.Column('activation_until', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"), nullable=False),
    sa.PrimaryKeyConstraint('target_id'),
    sa.UniqueConstraint('physical_index')
    )
    op.create_table('search_embedding_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('entity_key', sa.String(length=80), nullable=False),
    sa.Column('source_version', sa.BigInteger(), nullable=False),
    sa.Column('projection_hash', sa.String(length=64), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('available_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"), nullable=False),
    sa.Column('lease_token', sa.String(length=36), nullable=True),
    sa.Column('lease_until', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error_code', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"), nullable=False),
    sa.Column('finished_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_id', 'entity_key', 'source_version', 'profile_id', name='uq_search_embedding_version')
    )
    op.create_index('ix_search_embedding_pending', 'search_embedding_jobs', ['status', 'available_at', 'id'], unique=False)
    op.create_index('ix_search_embedding_lease', 'search_embedding_jobs', ['status', 'lease_until', 'id'], unique=False)
    op.create_table('search_backfill_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('stage', sa.String(length=16), nullable=False),
    sa.Column('boundary', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"), nullable=False),
    sa.Column('cursor', sa.JSON(), nullable=True),
    sa.Column('processed', sa.BigInteger(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('available_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"), nullable=False),
    sa.Column('lease_token', sa.String(length=36), nullable=True),
    sa.Column('lease_until', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error_code', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"), nullable=False),
    sa.Column('finished_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), "mysql"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade():
    op.drop_table("search_backfill_runs")
    op.drop_table("search_embedding_jobs")
    op.drop_table("search_index_targets")
    op.drop_table("search_embedding_profiles")
    op.drop_table("search_outbox")
    op.drop_table("search_document_states")
    op.drop_index("ix_chat_message_context", table_name="chat_messages")
    op.drop_column("chat_messages", "sort_seq")
    op.drop_column("sdd_tasks", "next_chat_seq")
