"""fix_missing_workspace_columns

Revision ID: e8b45809f6c4
Revises: b3a9fd9e1c1f
Create Date: 2026-03-24 16:00:25.941872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8b45809f6c4'
down_revision: Union[str, None] = 'b3a9fd9e1c1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('project_path', sa.String(length=500), nullable=True))
    op.add_column('workspaces', sa.Column('git_repo_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'git_repo_url')
    op.drop_column('workspaces', 'project_path')
    # ### end Alembic commands ###
