"""refactor_api_mock_persistence

Revision ID: eb996183c1d8
Revises: cf2f0e7c8e11
Create Date: 2026-03-28 15:19:57.179882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'eb996183c1d8'
down_revision: Union[str, None] = 'cf2f0e7c8e11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sdd_api_mock_endpoints', 'parameters_json')
    op.drop_column('sdd_api_mock_endpoints', 'responses_json')
    op.drop_column('sdd_api_mock_endpoints', 'request_schema_json')
    op.drop_column('sdd_api_mock_endpoints', 'entity_refs_json')
    op.drop_column('sdd_api_mock_endpoints', 'response_schema_json')
    op.add_column('sdd_api_mock_entities', sa.Column('endpoint_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_sdd_api_mock_entities_endpoint_id'), 'sdd_api_mock_entities', ['endpoint_id'], unique=False)
    op.create_foreign_key(None, 'sdd_api_mock_entities', 'sdd_api_mock_endpoints', ['endpoint_id'], ['id'], ondelete='SET NULL')
    op.drop_column('sdd_api_mock_entities', 'schema_json')
    op.add_column('sdd_api_mock_source_versions', sa.Column('storage_path', sa.String(length=1000), nullable=True))
    op.alter_column('sdd_api_mock_source_versions', 'raw_content',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               nullable=True)
    op.alter_column('sdd_api_mock_source_versions', 'normalized_oas_json',
               existing_type=mysql.JSON(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sdd_api_mock_source_versions', 'normalized_oas_json',
               existing_type=mysql.JSON(),
               nullable=False)
    op.alter_column('sdd_api_mock_source_versions', 'raw_content',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               nullable=False)
    op.drop_column('sdd_api_mock_source_versions', 'storage_path')
    op.add_column('sdd_api_mock_entities', sa.Column('schema_json', mysql.JSON(), nullable=False))
    op.drop_constraint(None, 'sdd_api_mock_entities', type_='foreignkey')
    op.drop_index(op.f('ix_sdd_api_mock_entities_endpoint_id'), table_name='sdd_api_mock_entities')
    op.drop_column('sdd_api_mock_entities', 'endpoint_id')
    op.add_column('sdd_api_mock_endpoints', sa.Column('response_schema_json', mysql.JSON(), nullable=True))
    op.add_column('sdd_api_mock_endpoints', sa.Column('entity_refs_json', mysql.JSON(), nullable=True))
    op.add_column('sdd_api_mock_endpoints', sa.Column('request_schema_json', mysql.JSON(), nullable=True))
    op.add_column('sdd_api_mock_endpoints', sa.Column('responses_json', mysql.JSON(), nullable=True))
    op.add_column('sdd_api_mock_endpoints', sa.Column('parameters_json', mysql.JSON(), nullable=True))
    # ### end Alembic commands ###
