"""
Agent 适配层。

阶段 2 契约骨架：
- contract.py   : AgentBackend / AgentRunRequest / AgentRunResult / AgentCapabilities
- events.py     : 统一 AgentEvent
- errors.py     : 统一异常
- registry.py   : Agent backend 注册与创建
- adapters/     : claude-code / opencode / dsh / mock 等实现
"""

from app.agents.contract import (
    EXECUTION_KIND_LOCAL_PROCESS,
    EXECUTION_KIND_REMOTE_SESSION,
    AgentAttemptContext,
    AgentAttemptRuntimeState,
    AgentBackend,
    AgentCapabilities,
    AgentEventSink,
    AgentProcessIdentity,
    AgentRunRequest,
    AgentRunResult,
    AgentStopResult,
    AttemptFinalizerEvidence,
    ExecutionKind,
    ProcessDeathState,
    ProcessTerminationEvidence,
    ProviderCallEvidence,
    ProviderCallState,
    ProviderStopEvidence,
    SkillRef,
    TokenUsage,
    agent_attempt_key,
    agent_process_identity_key,
    bind_agent_attempt,
    bind_agent_attempt_runtime,
    current_agent_attempt,
    current_agent_attempt_key,
    current_agent_attempt_runtime,
    mark_provider_call_unresolved,
    record_attempt_process_started,
    record_attempt_provider_call_stop,
    record_attempt_remote_session_started,
    record_attempt_remote_stop,
    record_attempt_termination,
    record_provider_call_result,
    record_provider_call_session_started,
    reset_agent_attempt,
    reset_agent_attempt_runtime,
)
from app.agents.errors import (
    AgentCancelledError,
    AgentConfigurationError,
    AgentError,
    AgentProtocolError,
    AgentProviderError,
    AgentTimeoutError,
)
from app.agents.events import AgentEvent

__all__ = [
    "AgentBackend",
    "AgentAttemptContext",
    "AgentAttemptRuntimeState",
    "AgentProcessIdentity",
    "AgentCapabilities",
    "AgentEvent",
    "AgentEventSink",
    "AgentStopResult",
    "AttemptFinalizerEvidence",
    "ExecutionKind",
    "EXECUTION_KIND_LOCAL_PROCESS",
    "EXECUTION_KIND_REMOTE_SESSION",
    "ProcessDeathState",
    "ProcessTerminationEvidence",
    "ProviderCallState",
    "ProviderCallEvidence",
    "ProviderStopEvidence",
    "agent_attempt_key",
    "agent_process_identity_key",
    "current_agent_attempt",
    "current_agent_attempt_key",
    "bind_agent_attempt",
    "reset_agent_attempt",
    "current_agent_attempt_runtime",
    "bind_agent_attempt_runtime",
    "reset_agent_attempt_runtime",
    "record_attempt_process_started",
    "record_attempt_termination",
    "record_attempt_remote_stop",
    "record_attempt_provider_call_stop",
    "record_attempt_remote_session_started",
    "record_provider_call_session_started",
    "record_provider_call_result",
    "mark_provider_call_unresolved",
    "AgentRunRequest",
    "AgentRunResult",
    "AgentCancelledError",
    "AgentConfigurationError",
    "AgentError",
    "AgentProtocolError",
    "AgentProviderError",
    "AgentTimeoutError",
    "SkillRef",
    "TokenUsage",
]
